docs:(signature/mail-2024-16-10.md) review
Simplon-hdf/API-bots-discord-documentation pull request #62
Opened 2024-10-16 14:03 UTC by YohanF1245

2024-10-16 14:34 UTC, aReynier approved these changes

2024-10-17 07:47 UTC, MessaKami requested changes
Nom du commit pas respecté revoir la nomenclature sur le readme du repo merci

2024-10-17 07:48 UTC, Martial59110 requested changes
The commit name is not correct; you should only put 'BotSignature' in the scope.

2024-10-17 07:52 UTC, EnguerranSGG requested changes
Der Commit-Name ist nicht korrekt; sie sollten nur "bot-signature“ in den Bereich einfügen.

2024-10-17 11:48 UTC, closed without merging