docs(): modify commit's rule
Simplon-hdf/API-bots-discord-documentation pull request #88
Opened 2024-10-21 14:04 UTC by EnguerranSGG

2024-10-21 14:06 UTC, Srekaens requested changes
change the scope pls

2024-10-21 14:07 UTC, Martial59110 requested changes
Add readme in scope

2024-10-21 14:07 UTC, julienbeauchant approved these changes

2024-10-21 14:08 UTC, BborisB approved these changes

2024-10-21 14:08 UTC, Srekaens approved these changes

2024-10-21 14:10 UTC, Srekaens submitted a review, later dismissed
faire le chenapan ne fonctionne pas

2024-10-21 14:20 UTC, julienbeauchant approved these changes

2024-10-22 07:21 UTC, Martial59110 approved these changes

2024-10-22 07:22 UTC, aReynier approved these changes

2024-10-22 07:27 UTC, BborisB approved these changes

2024-10-22 07:27 UTC, Srekaens approved these changes
Super Enguerran !

2024-10-22 07:27 UTC, BborisB approved these changes

2024-10-22 07:27 UTC, BborisB approved these changes

2024-10-22 07:27 UTC, Srekaens approved these changes

2024-10-22 07:27 UTC, merged